{% set version = "0.0.22" %}
{% set python_min = "3.10" %}

package:
  name: autotools-language-server
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/autotools-language-server/autotools_language_server-{{ version }}.tar.gz
  sha256: dea1dcfb6fc62a225371cd8e090953a368d12b23760037d6814d0dc48575afdf

build:
  entry_points:
    - make-language-server = make_language_server.__main__:main
    - autoconf-language-server = make_language_server.__main__:main
    - autotools-language-server = make_language_server.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ={{ python_min }}
    - setuptools
    - setuptools-scm >=6.2
    - setuptools-generate >=0.0.6
    - pip
  run:
    - python >={{ python_min }}
    - lsp-tree-sitter >=0.0.16
    - tree-sitter-make

test:
  imports:
    - autoconf_language_server
    - make_language_server
  commands:
    - pip check
    - make-language-server --help
    - autoconf-language-server --help
    - autotools-language-server --help
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/Freed-Wu/autotools-language-server
  summary: Language server for makefile and configure.ac
  dev_url: https://github.com/Freed-Wu/autotools-language-server
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
